language: node_js
node_js:
  - "7"
env:
- NODE_ENV=production
install:
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: AWS_SECRET
  bucket: "2017-astronautweb"  
