language: node_js
node_js:
  - "7"
env:
- NODE_ENV=production
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
script:
  - npm run build
deploy:
  #provider: s3
  provider: script
  script: ~/.local/bin/aws s3 sync dist s3://2017-astronautweb --region=ap-southeast-2 --delete --cache-control="max-age=31536000"
  #access_key_id: $AWS_ACCESS_KEY
  #secret_access_key: $AWS_SECRET
  #bucket: "2017-astronautweb"
  skip_cleanup: true
  #local_dir: dist
#  detect_encoding: true
  #cache_control: "max-age=31536000"
  #default_text_charset: "utf-8"
  #region: $AWS_DEFAULT_REGION
after_deploy:
  script: ~/.local/bin/aws s3 sync dist/*.html s3://2017-astronautweb --region=ap-southeast-2 --delete --cache-control="no-cache"

  # travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $CLOUDFRONT_DISTRIBUTION_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
  # Allow `awscli` to make requests to CloudFront.
  #- aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  #- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
