language: node_js
node_js:
  - "7"
env:
- NODE_ENV=production
install:
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "2017-astronautweb"
  skip_cleanup: true
  local_dir: dist
#  detect_encoding: true
  cache_control: "max-age=31536000"
  default_text_charset: "utf-8"
  region: $AWS_DEFAULT_REGION
#after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  #- aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  #- aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
