language: node_js
node_js:
  - "7"
env:
- NODE_ENV=production
install:
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: "AKIAI6DQTPSPOCLZ4NNA"
  secret_access_key: "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"
  bucket: "2017-astronautweb"
  skip_cleanup: true
