language: node_js
node_js:
  - "7"
env:
- NODE_ENV=production
install:
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: "AKIAJZAA5JIWRGOMXZAQ"
  secret_access_key: 
  bucket: "2017-astronautweb"
  skip_cleanup: true
